### ISSUE TITLE
Python mock library missing

### ISSUE THREAD

**Issue by kitchung** [andrey-yantsen/plexiglas#10]
FYI, I encountered this error when installing onto my WD My Passport Wireless Pro.

Running "pip install mock" solved the problem.

> ssh -t root@mypassport.local "LC_ALL=en_US.UTF-8 PYTHONHOME=/DataVolume/python/ /DataVolume/python/bin/plexiglas -d /DataVolume/PlexSync -i -n 'MyPassport Wireless Pro' -q"
> root@mypassport.local's password:
> Traceback (most recent call last):
>   File "/DataVolume/python/bin/plexiglas", line 8, in <module>
>     sys.exit(main())
>   File "/DataVolume/python/lib/python2.7/site-packages/plexiglas/cli.py", line 195, in main
>     from .content import cleanup
>   File "/DataVolume/python/lib/python2.7/site-packages/plexiglas/content.py", line 2, in <module>
>     from plexapi.exceptions import BadRequest
>   File "/DataVolume/python/lib/python2.7/site-packages/plexapi/__init__.py", line 6, in <module>
>     from plexapi.config import PlexConfig, reset_base_headers
>   File "/DataVolume/python/lib/python2.7/site-packages/plexapi/config.py", line 4, in <module>
>     from plexapi.compat import ConfigParser
>   File "/DataVolume/python/lib/python2.7/site-packages/plexapi/compat.py", line 50, in <module>
>     from mock import patch, MagicMock
> ImportError: No module named mock

**Comment by worried-networking** [comment]
Hm, thanks!
