### ISSUE TITLE
Sync unexpected file size error

### ISSUE THREAD

**Issue by Xalaxis** [andrey-yantsen/plexiglas#6]
When someone who is not the owner of the server tries the same sync as me, they get a file size mismatch.  Whatever their Plexiglas is downloading, it's tiny so it might be some kind of error message perhaps?

```
PS C:\Users\<name>\desktop> plexiglas --simple-sync-url https://app.plex.tv/desktop#!/server/<server id>/details?key=%2
Flibrary%2Fmetadata%2F32535
Please provide MyPlex login: <username>
Enter the plex.tv password for <password>:
[27/03/2019 22:06:11] [INFO] [plexiglas] Starting plexiglas version 0.4.2 on Windows 10...
[27/03/2019 22:06:11] [INFO] [plexiglas] Using myplex with username <username>
[27/03/2019 22:06:13] [INFO] [plexiglas] Downloading Elementary.s01e01.mkv to C:\Users\<name>\desktop\TV Shows, file size is 1.76 GiB
Elementary.s01e01.mkv.part: 91.0B [00:00, 18.2kB/s]
[27/03/2019 22:06:13] [ERROR] [plexiglas] File "C:\Users\<name>\desktop\TV Shows\Elementary.s01e01.mkv.part" has an unexpected size (actual: 91, expected: 1892482290)
[27/03/2019 22:06:13] [ERROR] [plexiglas] Unexpected error
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\plexiglas\cli.py", line 246, in main
    required_media = plugin.sync(plex, opts)
  File "c:\python27\lib\site-packages\plexiglas\simple_sync.py", line 130, in sync
    download_media(plex, section.title, item, part, opts, mark_downloaded, max_allowed_size_diff_percent)
  File "c:\python27\lib\site-packages\plexiglas\content.py", line 240, in download_media
    raise ValueError('Downloaded file size is not the same as expected')
ValueError: Downloaded file size is not the same as expected
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "main", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\plexiglas.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\plexiglas\cli.py", line 246, in main
    required_media = plugin.sync(plex, opts)
  File "c:\python27\lib\site-packages\plexiglas\simple_sync.py", line 130, in sync
    download_media(plex, section.title, item, part, opts, mark_downloaded, max_allowed_size_diff_percent)
  File "c:\python27\lib\site-packages\plexiglas\content.py", line 240, in download_media
    raise ValueError('Downloaded file size is not the same as expected')
ValueError: Downloaded file size is not the same as expected```

**Comment by worried-networking** [comment]
Yeah, I'll convert it to the more understandable error, thanks!

Unfortunately syncing with shared library is not supported yet — Plex doesn't provides link for downloading for shared libs.
